[package]
name = "symcrypt-sys"
authors = ["Microsoft"]
version = "0.4.0"
license = "MIT OR Apache-2.0"
description = "Rust/C Bindings for SymCrypt"
edition = "2021"
build = "build.rs"
homepage = "https://github.com/microsoft/SymCrypt"
repository = "https://github.com/microsoft/rust-symcrypt"
readme = "README.md"

[features]
default = []
# Build symcrypt statically
static = ["dep:cmake", "dep:gix"]

[dependencies]
libc = "0.2.0"

[build-dependencies]
cmake = { version = "0.1", optional = true }
gix = { version = "0.69", optional = true, features = [
    "blocking-network-client",
    "blocking-http-transport-reqwest-native-tls",
    "interrupt",
    "worktree-mutation",
] }
